{% set name = "python-crontab" %}
{% set version = "2.4.2" %}
{% set sha256 = "ed9583cff430715d9560cbad28309429ac13f3fdb13051ac2288050e05abc392" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil

test:
  imports:
    - crontab

about:
  home: https://github.com/doctormo/python-crontab
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Crontab module for reading and writing crontab files and accessing the system cron automatically and simply using a direct API.

extra:
  recipe-maintainers:
    - scopatz
