travis:
  secure:
    BINSTAR_TOKEN: WmrTomPlpEzF4Q+VmVL91OM5NcImqdr4oP1tuNmTQSk6rqMmmoEuJScyCQrqITQCzHuyI0Mw94u/Be3eUOvoIxaF36vg+WITgA4cQlhXWRNf1gjvPWreez3Aww01NvUXI/H+71UjGNi2q+1RXia5BqnotAp1aMAH39Sh/7or2PhZtlKrghzDs15B3x9zt1lonmHaxEQGaqh0NfnT9V3FQ8s9nJ0SBRO4g9ZYuQHAfhzTW4ytczK++1V4Rs1jVtkGP3WBgH0GTSygGZO46bXIhzCdwS0CgmC7VaDUF8r0cr84muHaO2St2qaAr1JaV8TPUtRdKxpzdkhtFWmtH+k14P7nRZSo9D+gvMSfZ5pHSdKy9Td9/Cxt6n6WMbfHv46edy9hLIBkVOB69/I4B5GFkkpYRjW//nsBqIkFerS2Ng5vbVNaQ3RG3Q0F2WfU8wDYyTFM+kuV4o1lyA5wxD02VQZ+x3T+bW11RhjO7tVSaEqp5YMcpAovYMBX1IrHjJSwAEa/ROt3iMB7XLbzu654862SSzyjXU8xIO8mIgk+wLgFh5x8FWhOF6Z9WW/0G2bjJbRtK/uBakKzxjeavTP6gq7i6+y+Xx6Or7Kxwc0beuosqc35u7EbC4DttHUqGKgtTsdhMK6BN0cGLdY6XVbQukC9MVKt2QZ85Tp3PcPJCBc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
