travis:
  secure:
    BINSTAR_TOKEN: NABFLdiXA3o1CLuNNIEyUY/M77f0dVIgECdHXyvpAE4jrIhVSYAAMHfnyfokThdIT0KBmTjfClQaYb+Un6ydG+0yDpJc7PvsziC04RacW3NTV0UziIvWlhMtUOKk6+d5WWitiNinOxHVbGvhhXRdMIjKSi5WAmoisYJDYkTo4wuvwxG+ar9sKySJr9LF1pc1yWhueheAbLsK7WbvyN3Nw5UCaKtL56vmjaOgXkJZZ0DCuptZZxxphfxx6ZENrctMdjGF89TUTkbTjz7lSAfcVztNIlFFBN5VM/p/lBNAL9JeHT0GjB3/H4gKvOpGOszvSwdCUuoOjIPwuJi3uctDL1g+ITan7JOOG97bjv0SagGUKL1C0qVidPoLq+6PAb1ySUvjJTUT0lWFE3lh1iZHDtMoZRlp59eSGW7NV46XpQlvJ+eAgLVAGA+LpbThBhZ9U6FVId+sPS9cwwT5oEFSvOVtYR60OKEWTyeSqgl9ePXQWFKCbTS6+LPyXcJja8VzK61HqGsZk0CL5rpWXd3waAph4LTdTRbn6fywPniRDEe2n/JFTd9G9GueoE5wR4fxc7Ksp/UblgsfJHxX9GIZ1+rDxZwfPDqnuKHw8ZS+55+47wqz4Tq8YTtlngvcp8+NSqelXVrnQZx2cnsGHC0ejWObFbIoc3P+ja/q1/9WaTE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
